"""initial production schema

Revision ID: 2cf3891f064c
Revises:
Create Date: 2026-07-31 03:57:05.437373
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2cf3891f064c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_definitions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rule_type", sa.String(length=32), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rule_type IN ('price_return', 'volume_spike', 'new_high')",
            name=op.f("ck_event_definitions_valid_event_rule_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_definitions")),
        sa.UniqueConstraint("name", "version", name="uq_event_definitions_name_version"),
    )
    op.create_index(
        "ix_event_definitions_active_type",
        "event_definitions",
        ["is_active", "rule_type"],
        unique=False,
    )
    op.create_table(
        "factor_research_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("analysis_type", sa.String(length=16), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "analysis_type IN ('snapshot', 'backtest')",
            name=op.f("ck_factor_research_runs_valid_factor_analysis_type"),
        ),
        sa.CheckConstraint(
            "market IN ('A', 'HK', 'US')", name=op.f("ck_factor_research_runs_valid_factor_market")
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_factor_research_runs_valid_factor_run_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_research_runs")),
    )
    op.create_index(
        "ix_factor_runs_type_created",
        "factor_research_runs",
        ["analysis_type", "created_at"],
        unique=False,
    )
    op.create_table(
        "fx_rates",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "base_currency <> quote_currency", name=op.f("ck_fx_rates_distinct_fx_currencies")
        ),
        sa.CheckConstraint("rate > 0", name=op.f("ck_fx_rates_positive_fx_rate")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fx_rates")),
        sa.UniqueConstraint(
            "base_currency",
            "quote_currency",
            "rate_date",
            "source",
            name="uq_fx_rate_pair_date_source",
        ),
    )
    op.create_index(
        "ix_fx_rates_pair_date",
        "fx_rates",
        ["base_currency", "quote_currency", "rate_date"],
        unique=False,
    )
    op.create_table(
        "industries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taxonomy", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["industries.id"], name=op.f("fk_industries_parent_id_industries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_industries")),
        sa.UniqueConstraint("taxonomy", "code", name="uq_industries_taxonomy_code"),
    )
    op.create_table(
        "lead_lag_analysis_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("maximum_lag_days", sa.Integer(), nullable=False),
        sa.Column("minimum_observations", sa.Integer(), nullable=False),
        sa.Column("fdr_alpha", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("minimum_abs_correlation", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_lead_lag_analysis_runs_valid_lead_lag_status"),
        ),
        sa.CheckConstraint(
            "fdr_alpha > 0 AND fdr_alpha < 1",
            name=op.f("ck_lead_lag_analysis_runs_valid_lead_lag_fdr"),
        ),
        sa.CheckConstraint(
            "maximum_lag_days > 0", name=op.f("ck_lead_lag_analysis_runs_positive_lead_lag_max_lag")
        ),
        sa.CheckConstraint(
            "minimum_abs_correlation >= 0 AND minimum_abs_correlation <= 1",
            name=op.f("ck_lead_lag_analysis_runs_valid_lead_lag_correlation_threshold"),
        ),
        sa.CheckConstraint(
            "minimum_observations >= 10",
            name=op.f("ck_lead_lag_analysis_runs_valid_lead_lag_minimum_observations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_lag_analysis_runs")),
    )
    op.create_index(
        "ix_lead_lag_runs_end_created",
        "lead_lag_analysis_runs",
        ["end_date", "created_at"],
        unique=False,
    )
    op.create_table(
        "market_graph_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_market_graph_runs_valid_market_graph_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_graph_runs")),
    )
    op.create_index(
        "ix_market_graph_runs_end_created",
        "market_graph_runs",
        ["end_date", "created_at"],
        unique=False,
    )
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("name", name=op.f("uq_portfolios_name")),
    )
    op.create_table(
        "relationship_analysis_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("universe_type", sa.String(length=16), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('pearson', 'spearman')",
            name=op.f("ck_relationship_analysis_runs_valid_relationship_method"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_relationship_analysis_runs_valid_relationship_status"),
        ),
        sa.CheckConstraint(
            "universe_type IN ('stock', 'etf', 'industry')",
            name=op.f("ck_relationship_analysis_runs_valid_universe_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_analysis_runs")),
    )
    op.create_index(
        "ix_relationship_runs_universe_method_created",
        "relationship_analysis_runs",
        ["universe_type", "method", "created_at"],
        unique=False,
    )
    op.create_table(
        "research_reports",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("subject_key", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("data_sources", sa.JSON(), nullable=False),
        sa.Column("methodology", sa.JSON(), nullable=False),
        sa.Column("risk_factors", sa.JSON(), nullable=False),
        sa.Column("generated_by", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_reports")),
    )
    op.create_index(
        op.f("ix_research_reports_as_of_date"), "research_reports", ["as_of_date"], unique=False
    )
    op.create_index(
        op.f("ix_research_reports_report_type"), "research_reports", ["report_type"], unique=False
    )
    op.create_table(
        "factor_backtest_periods",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("rebalance_date", sa.Date(), nullable=False),
        sa.Column("period_end_date", sa.Date(), nullable=False),
        sa.Column("selected_stock_ids", sa.JSON(), nullable=False),
        sa.Column("selected_symbols", sa.JSON(), nullable=False),
        sa.Column("selected_count", sa.Integer(), nullable=False),
        sa.Column("portfolio_return", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("benchmark_return", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("excess_return", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.CheckConstraint(
            "selected_count > 0",
            name=op.f("ck_factor_backtest_periods_positive_factor_selected_count"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["factor_research_runs.id"],
            name=op.f("fk_factor_backtest_periods_run_id_factor_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_backtest_periods")),
        sa.UniqueConstraint("run_id", "rebalance_date", name="uq_factor_backtest_run_rebalance"),
    )
    op.create_index(
        "ix_factor_backtest_period_run_date",
        "factor_backtest_periods",
        ["run_id", "rebalance_date"],
        unique=False,
    )
    op.create_table(
        "factor_backtest_summaries",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("period_count", sa.Integer(), nullable=False),
        sa.Column("cumulative_return", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column(
            "benchmark_cumulative_return", sa.Numeric(precision=18, scale=10), nullable=False
        ),
        sa.Column("annualized_return", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("annualized_volatility", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("sharpe_ratio", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("max_drawdown", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("excess_hit_rate", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.CheckConstraint(
            "period_count > 0",
            name=op.f("ck_factor_backtest_summaries_positive_factor_period_count"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["factor_research_runs.id"],
            name=op.f("fk_factor_backtest_summaries_run_id_factor_research_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_backtest_summaries")),
        sa.UniqueConstraint("run_id", name=op.f("uq_factor_backtest_summaries_run_id")),
    )
    op.create_table(
        "market_graph_paths",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("path_rank", sa.Integer(), nullable=False),
        sa.Column("node_keys", sa.JSON(), nullable=False),
        sa.Column("node_labels", sa.JSON(), nullable=False),
        sa.Column("relationship_types", sa.JSON(), nullable=False),
        sa.Column("aggregate_strength", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("total_lag_days", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "aggregate_strength >= 0 AND aggregate_strength <= 1",
            name=op.f("ck_market_graph_paths_valid_path_strength"),
        ),
        sa.CheckConstraint(
            "path_rank > 0", name=op.f("ck_market_graph_paths_positive_graph_path_rank")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["market_graph_runs.id"],
            name=op.f("fk_market_graph_paths_run_id_market_graph_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_graph_paths")),
        sa.UniqueConstraint("run_id", "path_rank", name="uq_market_graph_paths_run_rank"),
    )
    op.create_table(
        "relationship_anomalies",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("left_entity_type", sa.String(length=16), nullable=False),
        sa.Column("left_entity_id", sa.Integer(), nullable=False),
        sa.Column("left_entity_key", sa.String(length=96), nullable=False),
        sa.Column("left_entity_label", sa.String(length=256), nullable=False),
        sa.Column("right_entity_type", sa.String(length=16), nullable=False),
        sa.Column("right_entity_id", sa.Integer(), nullable=False),
        sa.Column("right_entity_key", sa.String(length=96), nullable=False),
        sa.Column("right_entity_label", sa.String(length=256), nullable=False),
        sa.Column("detected_on", sa.Date(), nullable=False),
        sa.Column("baseline_window_days", sa.Integer(), nullable=False),
        sa.Column("current_window_days", sa.Integer(), nullable=False),
        sa.Column("baseline_correlation", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("current_correlation", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("absolute_change", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("baseline_sample_size", sa.Integer(), nullable=False),
        sa.Column("current_sample_size", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "direction IN ('strengthened', 'weakened', 'sign_flip')",
            name=op.f("ck_relationship_anomalies_valid_relationship_direction"),
        ),
        sa.CheckConstraint(
            "absolute_change >= 0",
            name=op.f("ck_relationship_anomalies_nonnegative_absolute_change"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["relationship_analysis_runs.id"],
            name=op.f("fk_relationship_anomalies_run_id_relationship_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_anomalies")),
    )
    op.create_index(
        "ix_relationship_anomalies_run_change",
        "relationship_anomalies",
        ["run_id", "absolute_change"],
        unique=False,
    )
    op.create_table(
        "relationship_correlations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("left_entity_type", sa.String(length=16), nullable=False),
        sa.Column("left_entity_id", sa.Integer(), nullable=False),
        sa.Column("left_entity_key", sa.String(length=96), nullable=False),
        sa.Column("left_entity_label", sa.String(length=256), nullable=False),
        sa.Column("right_entity_type", sa.String(length=16), nullable=False),
        sa.Column("right_entity_id", sa.Integer(), nullable=False),
        sa.Column("right_entity_key", sa.String(length=96), nullable=False),
        sa.Column("right_entity_label", sa.String(length=256), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("correlation", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "left_entity_type IN ('stock', 'etf', 'industry')",
            name=op.f("ck_relationship_correlations_valid_left_entity_type"),
        ),
        sa.CheckConstraint(
            "right_entity_type IN ('stock', 'etf', 'industry')",
            name=op.f("ck_relationship_correlations_valid_right_entity_type"),
        ),
        sa.CheckConstraint(
            "correlation >= -1 AND correlation <= 1",
            name=op.f("ck_relationship_correlations_valid_correlation"),
        ),
        sa.CheckConstraint(
            "sample_size >= 2", name=op.f("ck_relationship_correlations_valid_sample_size")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["relationship_analysis_runs.id"],
            name=op.f("fk_relationship_correlations_run_id_relationship_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_correlations")),
        sa.UniqueConstraint(
            "run_id",
            "left_entity_key",
            "right_entity_key",
            "window_days",
            "as_of_date",
            name="uq_relationship_correlation_observation",
        ),
    )
    op.create_index(
        "ix_relationship_correlations_pair_date",
        "relationship_correlations",
        ["left_entity_key", "right_entity_key", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("canonical_code", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("exchange", sa.String(length=16), nullable=False),
        sa.Column("asset_type", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("delist_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("industry_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "asset_type IN ('stock', 'etf', 'index', 'commodity')",
            name=op.f("ck_stocks_valid_asset_type"),
        ),
        sa.CheckConstraint("market IN ('A', 'HK', 'US')", name=op.f("ck_stocks_valid_market")),
        sa.ForeignKeyConstraint(
            ["industry_id"], ["industries.id"], name=op.f("fk_stocks_industry_id_industries")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stocks")),
        sa.UniqueConstraint("canonical_code", name=op.f("uq_stocks_canonical_code")),
        sa.UniqueConstraint("exchange", "symbol", name="uq_stocks_exchange_symbol"),
    )
    op.create_index(op.f("ix_stocks_industry_id"), "stocks", ["industry_id"], unique=False)
    op.create_index("ix_stocks_market_status", "stocks", ["market", "is_active"], unique=False)
    op.create_table(
        "event_study_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "definition_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("trigger_stock_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("horizons", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_event_study_runs_valid_event_study_status"),
        ),
        sa.ForeignKeyConstraint(
            ["definition_id"],
            ["event_definitions.id"],
            name=op.f("fk_event_study_runs_definition_id_event_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["trigger_stock_id"],
            ["stocks.id"],
            name=op.f("fk_event_study_runs_trigger_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_study_runs")),
    )
    op.create_index(
        "ix_event_study_runs_definition_created",
        "event_study_runs",
        ["definition_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_events_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_type_time", "events", ["event_type", "occurred_at"], unique=False)
    op.create_table(
        "factor_scores",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("raw_factors", sa.JSON(), nullable=False),
        sa.Column("normalized_factors", sa.JSON(), nullable=False),
        sa.Column("category_scores", sa.JSON(), nullable=False),
        sa.Column("factor_score", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("category_coverage", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "category_coverage >= 1 AND category_coverage <= 5",
            name=op.f("ck_factor_scores_valid_factor_category_coverage"),
        ),
        sa.CheckConstraint(
            "factor_score >= 0 AND factor_score <= 100",
            name=op.f("ck_factor_scores_valid_composite_factor_score"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["factor_research_runs.id"],
            name=op.f("fk_factor_scores_run_id_factor_research_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_factor_scores_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_factor_scores")),
        sa.UniqueConstraint(
            "run_id", "as_of_date", "stock_id", name="uq_factor_scores_run_date_stock"
        ),
    )
    op.create_index(
        "ix_factor_scores_run_date_score",
        "factor_scores",
        ["run_id", "as_of_date", "factor_score"],
        unique=False,
    )
    op.create_table(
        "financials",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revenue", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("net_income", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("operating_cash_flow", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("free_cash_flow", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("roe", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("roic", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("gross_margin", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("debt_ratio", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("pe", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("pb", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("ps", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("peg", sa.Numeric(precision=16, scale=6), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "period_type IN ('annual', 'quarterly', 'ttm')",
            name=op.f("ck_financials_valid_period_type"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"],
            ["stocks.id"],
            name=op.f("fk_financials_stock_id_stocks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financials")),
        sa.UniqueConstraint(
            "stock_id",
            "period_end",
            "period_type",
            "source",
            name="uq_financials_stock_period_source",
        ),
    )
    op.create_index(
        "ix_financials_stock_available", "financials", ["stock_id", "available_at"], unique=False
    )
    op.create_table(
        "lead_lag_pair_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_stock_id", sa.Integer(), nullable=False),
        sa.Column("target_stock_id", sa.Integer(), nullable=False),
        sa.Column("best_lag_days", sa.Integer(), nullable=False),
        sa.Column("cross_correlation", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("granger_f_statistic", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("raw_p_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("lag_adjusted_p_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("q_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("is_significant", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "best_lag_days > 0", name=op.f("ck_lead_lag_pair_results_positive_lead_lag_best_lag")
        ),
        sa.CheckConstraint(
            "confidence_score >= 0 AND confidence_score <= 1",
            name=op.f("ck_lead_lag_pair_results_valid_lead_lag_confidence"),
        ),
        sa.CheckConstraint(
            "cross_correlation >= -1 AND cross_correlation <= 1",
            name=op.f("ck_lead_lag_pair_results_valid_lead_lag_cross_correlation"),
        ),
        sa.CheckConstraint(
            "lag_adjusted_p_value >= 0 AND lag_adjusted_p_value <= 1",
            name=op.f("ck_lead_lag_pair_results_valid_lead_lag_adjusted_p"),
        ),
        sa.CheckConstraint(
            "q_value >= 0 AND q_value <= 1", name=op.f("ck_lead_lag_pair_results_valid_lead_lag_q")
        ),
        sa.CheckConstraint(
            "raw_p_value >= 0 AND raw_p_value <= 1",
            name=op.f("ck_lead_lag_pair_results_valid_lead_lag_raw_p"),
        ),
        sa.CheckConstraint(
            "sample_size >= 10", name=op.f("ck_lead_lag_pair_results_valid_lead_lag_pair_sample")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["lead_lag_analysis_runs.id"],
            name=op.f("fk_lead_lag_pair_results_run_id_lead_lag_analysis_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_stock_id"],
            ["stocks.id"],
            name=op.f("fk_lead_lag_pair_results_source_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["target_stock_id"],
            ["stocks.id"],
            name=op.f("fk_lead_lag_pair_results_target_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_lag_pair_results")),
        sa.UniqueConstraint(
            "run_id", "source_stock_id", "target_stock_id", name="uq_lead_lag_pair_run_direction"
        ),
    )
    op.create_index(
        "ix_lead_lag_pair_run_significant_confidence",
        "lead_lag_pair_results",
        ["run_id", "is_significant", "confidence_score"],
        unique=False,
    )
    op.create_table(
        "market_graph_edges",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("source_stock_id", sa.Integer(), nullable=False),
        sa.Column("target_stock_id", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("weight", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("strength", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "relationship_type IN ('correlation', 'lead_lag', 'capital_transmission')",
            name=op.f("ck_market_graph_edges_valid_market_graph_relationship"),
        ),
        sa.CheckConstraint(
            "lag_days >= 0", name=op.f("ck_market_graph_edges_nonnegative_graph_lag")
        ),
        sa.CheckConstraint(
            "sample_size >= 2", name=op.f("ck_market_graph_edges_valid_graph_sample_size")
        ),
        sa.CheckConstraint(
            "strength >= 0 AND strength <= 1",
            name=op.f("ck_market_graph_edges_valid_graph_strength"),
        ),
        sa.CheckConstraint(
            "weight >= -1 AND weight <= 1", name=op.f("ck_market_graph_edges_valid_graph_weight")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["market_graph_runs.id"],
            name=op.f("fk_market_graph_edges_run_id_market_graph_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_graph_edges_source_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["target_stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_graph_edges_target_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_graph_edges")),
        sa.UniqueConstraint(
            "run_id",
            "source_stock_id",
            "target_stock_id",
            "relationship_type",
            name="uq_market_graph_edges_run_pair_type",
        ),
    )
    op.create_index(
        "ix_market_graph_edges_run_type_strength",
        "market_graph_edges",
        ["run_id", "relationship_type", "strength"],
        unique=False,
    )
    op.create_table(
        "market_graph_nodes",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("node_key", sa.String(length=96), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("asset_type", sa.String(length=16), nullable=False),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("degree_centrality", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("betweenness_centrality", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("influence", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("association_strength", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("core_score", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("position_x", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("position_y", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.CheckConstraint(
            "asset_type IN ('stock', 'etf', 'index', 'commodity')",
            name=op.f("ck_market_graph_nodes_valid_market_graph_asset_type"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["market_graph_runs.id"],
            name=op.f("fk_market_graph_nodes_run_id_market_graph_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_market_graph_nodes_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_graph_nodes")),
        sa.UniqueConstraint("run_id", "stock_id", name="uq_market_graph_nodes_run_stock"),
    )
    op.create_index(
        "ix_market_graph_nodes_run_core",
        "market_graph_nodes",
        ["run_id", "core_score"],
        unique=False,
    )
    op.create_table(
        "market_regime_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("market", sa.String(length=8), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("vix_stock_id", sa.Integer(), nullable=False),
        sa.Column("rate_stock_id", sa.Integer(), nullable=False),
        sa.Column("dollar_stock_id", sa.Integer(), nullable=False),
        sa.Column("benchmark_stock_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market IN ('A', 'HK', 'US')", name=op.f("ck_market_regime_runs_valid_regime_market")
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_market_regime_runs_valid_market_regime_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_regime_runs_benchmark_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["dollar_stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_regime_runs_dollar_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["rate_stock_id"],
            ["stocks.id"],
            name=op.f("fk_market_regime_runs_rate_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["vix_stock_id"], ["stocks.id"], name=op.f("fk_market_regime_runs_vix_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_regime_runs")),
    )
    op.create_index(
        "ix_market_regime_runs_end_created",
        "market_regime_runs",
        ["end_date", "created_at"],
        unique=False,
    )
    op.create_table(
        "portfolio_positions",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("average_cost", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_positions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_portfolio_positions_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_positions")),
        sa.UniqueConstraint(
            "portfolio_id", "stock_id", "as_of_date", name="uq_positions_portfolio_stock_date"
        ),
    )
    op.create_table(
        "portfolio_risk_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("benchmark_stock_id", sa.Integer(), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_portfolio_risk_runs_valid_portfolio_risk_run_status"),
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_stock_id"],
            ["stocks.id"],
            name=op.f("fk_portfolio_risk_runs_benchmark_stock_id_stocks"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_risk_runs_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_risk_runs")),
    )
    op.create_index(
        "ix_portfolio_risk_runs_portfolio_created",
        "portfolio_risk_runs",
        ["portfolio_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=24, scale=4), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("adjustment_method", sa.String(length=32), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("high >= low", name=op.f("ck_prices_high_not_below_low")),
        sa.CheckConstraint(
            "volume IS NULL OR volume >= 0", name=op.f("ck_prices_nonnegative_volume")
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_prices_stock_id_stocks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
        sa.UniqueConstraint("stock_id", "trade_date", "source", name="uq_prices_stock_date_source"),
    )
    op.create_index("ix_prices_stock_date", "prices", ["stock_id", "trade_date"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("stock_id", sa.Integer(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("signal_type", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('long', 'short', 'neutral')", name=op.f("ck_signals_valid_direction")
        ),
        sa.ForeignKeyConstraint(
            ["stock_id"], ["stocks.id"], name=op.f("fk_signals_stock_id_stocks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index("ix_signals_stock_time", "signals", ["stock_id", "generated_at"], unique=False)
    op.create_table(
        "conditional_probability_runs",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "event_study_run_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("outcome_direction", sa.String(length=8), nullable=False),
        sa.Column("outcome_threshold", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("minimum_sample_size", sa.Integer(), nullable=False),
        sa.Column("confidence_level", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome_direction IN ('up', 'down')",
            name=op.f("ck_conditional_probability_runs_valid_conditional_direction"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'completed', 'failed')",
            name=op.f("ck_conditional_probability_runs_valid_conditional_status"),
        ),
        sa.CheckConstraint(
            "confidence_level > 0 AND confidence_level < 1",
            name=op.f("ck_conditional_probability_runs_valid_confidence_level"),
        ),
        sa.CheckConstraint(
            "minimum_sample_size >= 2",
            name=op.f("ck_conditional_probability_runs_valid_minimum_sample_size"),
        ),
        sa.CheckConstraint(
            "outcome_threshold >= 0",
            name=op.f("ck_conditional_probability_runs_nonnegative_outcome_threshold"),
        ),
        sa.ForeignKeyConstraint(
            ["event_study_run_id"],
            ["event_study_runs.id"],
            name=op.f("fk_conditional_probability_runs_event_study_run_id_event_study_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conditional_probability_runs")),
        sa.UniqueConstraint(
            "event_study_run_id",
            "outcome_direction",
            "outcome_threshold",
            "minimum_sample_size",
            "confidence_level",
            name="uq_conditional_probability_run_specification",
        ),
    )
    op.create_index(
        "ix_conditional_probability_runs_created",
        "conditional_probability_runs",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "event_occurrences",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("trigger_stock_id", sa.Integer(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("trigger_value", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("reference_value", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["event_study_runs.id"],
            name=op.f("fk_event_occurrences_run_id_event_study_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["trigger_stock_id"],
            ["stocks.id"],
            name=op.f("fk_event_occurrences_trigger_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_occurrences")),
        sa.UniqueConstraint("run_id", "event_date", name="uq_event_occurrences_run_date"),
    )
    op.create_index(
        "ix_event_occurrences_stock_date",
        "event_occurrences",
        ["trigger_stock_id", "event_date"],
        unique=False,
    )
    op.create_table(
        "event_study_statistics",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_stock_id", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("positive_probability", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("win_rate", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("average_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("median_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("return_stddev", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("best_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("worst_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("average_max_upside", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("best_max_upside", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("average_max_drawdown", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("worst_max_drawdown", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.CheckConstraint(
            "horizon_days > 0", name=op.f("ck_event_study_statistics_positive_statistic_horizon")
        ),
        sa.CheckConstraint(
            "positive_probability >= 0 AND positive_probability <= 1",
            name=op.f("ck_event_study_statistics_valid_positive_probability"),
        ),
        sa.CheckConstraint(
            "sample_size > 0", name=op.f("ck_event_study_statistics_positive_event_sample_size")
        ),
        sa.CheckConstraint(
            "win_rate >= 0 AND win_rate <= 1",
            name=op.f("ck_event_study_statistics_valid_event_win_rate"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["event_study_runs.id"],
            name=op.f("fk_event_study_statistics_run_id_event_study_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_stock_id"],
            ["stocks.id"],
            name=op.f("fk_event_study_statistics_target_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_study_statistics")),
        sa.UniqueConstraint(
            "run_id",
            "target_stock_id",
            "horizon_days",
            name="uq_event_statistics_run_target_horizon",
        ),
    )
    op.create_index(
        "ix_event_statistics_run_horizon",
        "event_study_statistics",
        ["run_id", "horizon_days"],
        unique=False,
    )
    op.create_table(
        "financial_per_share_metrics",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "financial_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("eps", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("diluted_eps", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("shares_outstanding", sa.Numeric(precision=28, scale=4), nullable=True),
        sa.CheckConstraint(
            "shares_outstanding IS NULL OR shares_outstanding > 0",
            name=op.f("ck_financial_per_share_metrics_positive_factor_shares_outstanding"),
        ),
        sa.ForeignKeyConstraint(
            ["financial_id"],
            ["financials.id"],
            name=op.f("fk_financial_per_share_metrics_financial_id_financials"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_financial_per_share_metrics")),
        sa.UniqueConstraint(
            "financial_id", name=op.f("uq_financial_per_share_metrics_financial_id")
        ),
    )
    op.create_table(
        "lead_lag_metrics",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "pair_result_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("lag_days", sa.Integer(), nullable=False),
        sa.Column("cross_correlation", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("granger_f_statistic", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("granger_p_value", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "cross_correlation >= -1 AND cross_correlation <= 1",
            name=op.f("ck_lead_lag_metrics_valid_lead_lag_metric_correlation"),
        ),
        sa.CheckConstraint(
            "granger_p_value >= 0 AND granger_p_value <= 1",
            name=op.f("ck_lead_lag_metrics_valid_lead_lag_metric_p"),
        ),
        sa.CheckConstraint(
            "lag_days > 0", name=op.f("ck_lead_lag_metrics_positive_lead_lag_metric_lag")
        ),
        sa.CheckConstraint(
            "sample_size >= 2", name=op.f("ck_lead_lag_metrics_valid_lead_lag_metric_sample")
        ),
        sa.ForeignKeyConstraint(
            ["pair_result_id"],
            ["lead_lag_pair_results.id"],
            name=op.f("fk_lead_lag_metrics_pair_result_id_lead_lag_pair_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_lag_metrics")),
        sa.UniqueConstraint("pair_result_id", "lag_days", name="uq_lead_lag_metric_pair_lag"),
    )
    op.create_table(
        "market_regime_observations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column("risk_on_probability", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("risk_off_probability", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("neutral_probability", sa.Numeric(precision=18, scale=16), nullable=False),
        sa.Column("composite_score", sa.Numeric(precision=16, scale=10), nullable=False),
        sa.Column("breadth_constituent_count", sa.Integer(), nullable=False),
        sa.Column("feature_values", sa.JSON(), nullable=False),
        sa.Column("feature_zscores", sa.JSON(), nullable=False),
        sa.Column("feature_contributions", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "regime IN ('risk_on', 'risk_off', 'neutral')",
            name=op.f("ck_market_regime_observations_valid_market_regime"),
        ),
        sa.CheckConstraint(
            "breadth_constituent_count > 0",
            name=op.f("ck_market_regime_observations_positive_regime_breadth_count"),
        ),
        sa.CheckConstraint(
            "neutral_probability >= 0 AND neutral_probability <= 1",
            name=op.f("ck_market_regime_observations_valid_neutral_probability"),
        ),
        sa.CheckConstraint(
            "risk_off_probability >= 0 AND risk_off_probability <= 1",
            name=op.f("ck_market_regime_observations_valid_risk_off_probability"),
        ),
        sa.CheckConstraint(
            "risk_on_probability >= 0 AND risk_on_probability <= 1",
            name=op.f("ck_market_regime_observations_valid_risk_on_probability"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["market_regime_runs.id"],
            name=op.f("fk_market_regime_observations_run_id_market_regime_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_regime_observations")),
        sa.UniqueConstraint("run_id", "as_of_date", name="uq_market_regime_run_date"),
    )
    op.create_index(
        "ix_market_regime_observations_run_date",
        "market_regime_observations",
        ["run_id", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "portfolio_risk_metrics",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("annualized_return", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("annualized_volatility", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("max_drawdown", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("sharpe_ratio", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("beta", sa.Numeric(precision=18, scale=10), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("industry_exposure", sa.JSON(), nullable=False),
        sa.Column("currency_exposure", sa.JSON(), nullable=False),
        sa.Column("position_weights", sa.JSON(), nullable=False),
        sa.Column("position_risks", sa.JSON(), nullable=False),
        sa.Column("equity_curve", sa.JSON(), nullable=False),
        sa.Column("drawdown_curve", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["portfolio_risk_runs.id"],
            name=op.f("fk_portfolio_risk_metrics_run_id_portfolio_risk_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_risk_metrics")),
        sa.UniqueConstraint("run_id", name=op.f("uq_portfolio_risk_metrics_run_id")),
    )
    op.create_table(
        "portfolio_stress_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("scenario_name", sa.String(length=128), nullable=False),
        sa.Column("benchmark_shock", sa.Numeric(precision=12, scale=8), nullable=False),
        sa.Column("currency_shocks", sa.JSON(), nullable=False),
        sa.Column("stressed_value", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("pnl_amount", sa.Numeric(precision=24, scale=4), nullable=False),
        sa.Column("pnl_percent", sa.Numeric(precision=18, scale=10), nullable=False),
        sa.Column("uncovered_weight", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("position_impacts", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "uncovered_weight >= 0 AND uncovered_weight <= 1",
            name=op.f("ck_portfolio_stress_results_valid_stress_uncovered_weight"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["portfolio_risk_runs.id"],
            name=op.f("fk_portfolio_stress_results_run_id_portfolio_risk_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_stress_results")),
        sa.UniqueConstraint("run_id", "scenario_name", name="uq_portfolio_stress_run_scenario"),
    )
    op.create_table(
        "conditional_probability_results",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("run_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("target_stock_id", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("meets_minimum", sa.Boolean(), nullable=False),
        sa.Column("probability", sa.Numeric(precision=12, scale=10), nullable=True),
        sa.Column("confidence_lower", sa.Numeric(precision=12, scale=10), nullable=True),
        sa.Column("confidence_upper", sa.Numeric(precision=12, scale=10), nullable=True),
        sa.Column("average_return", sa.Numeric(precision=20, scale=10), nullable=True),
        sa.CheckConstraint(
            "confidence_lower IS NULL OR (confidence_lower >= 0 AND confidence_lower <= 1)",
            name=op.f("ck_conditional_probability_results_valid_confidence_lower"),
        ),
        sa.CheckConstraint(
            "confidence_upper IS NULL OR (confidence_upper >= 0 AND confidence_upper <= 1)",
            name=op.f("ck_conditional_probability_results_valid_confidence_upper"),
        ),
        sa.CheckConstraint(
            "horizon_days > 0",
            name=op.f("ck_conditional_probability_results_positive_conditional_horizon"),
        ),
        sa.CheckConstraint(
            "probability IS NULL OR (probability >= 0 AND probability <= 1)",
            name=op.f("ck_conditional_probability_results_valid_conditional_probability"),
        ),
        sa.CheckConstraint(
            "sample_size >= 0",
            name=op.f("ck_conditional_probability_results_nonnegative_conditional_sample"),
        ),
        sa.CheckConstraint(
            "success_count <= sample_size",
            name=op.f("ck_conditional_probability_results_success_count_not_above_sample"),
        ),
        sa.CheckConstraint(
            "success_count >= 0",
            name=op.f("ck_conditional_probability_results_nonnegative_success_count"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["conditional_probability_runs.id"],
            name=op.f("fk_conditional_probability_results_run_id_conditional_probability_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_stock_id"],
            ["stocks.id"],
            name=op.f("fk_conditional_probability_results_target_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conditional_probability_results")),
        sa.UniqueConstraint(
            "run_id",
            "target_stock_id",
            "horizon_days",
            name="uq_conditional_results_run_target_horizon",
        ),
    )
    op.create_index(
        "ix_conditional_results_run_horizon",
        "conditional_probability_results",
        ["run_id", "horizon_days"],
        unique=False,
    )
    op.create_table(
        "event_study_observations",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column(
            "occurrence_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("target_stock_id", sa.Integer(), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("baseline_date", sa.Date(), nullable=False),
        sa.Column("horizon_date", sa.Date(), nullable=False),
        sa.Column("forward_return", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("max_upside", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("max_drawdown", sa.Numeric(precision=20, scale=10), nullable=False),
        sa.Column("is_win", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "forward_return > -1", name=op.f("ck_event_study_observations_valid_forward_return")
        ),
        sa.CheckConstraint(
            "horizon_days > 0", name=op.f("ck_event_study_observations_positive_event_horizon")
        ),
        sa.CheckConstraint(
            "max_drawdown >= -1 AND max_drawdown <= 0",
            name=op.f("ck_event_study_observations_valid_event_max_drawdown"),
        ),
        sa.CheckConstraint(
            "max_upside >= 0", name=op.f("ck_event_study_observations_nonnegative_max_upside")
        ),
        sa.ForeignKeyConstraint(
            ["occurrence_id"],
            ["event_occurrences.id"],
            name=op.f("fk_event_study_observations_occurrence_id_event_occurrences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_stock_id"],
            ["stocks.id"],
            name=op.f("fk_event_study_observations_target_stock_id_stocks"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_study_observations")),
        sa.UniqueConstraint(
            "occurrence_id",
            "target_stock_id",
            "horizon_days",
            name="uq_event_observations_occurrence_target_horizon",
        ),
    )
    op.create_index(
        "ix_event_observations_target_horizon",
        "event_study_observations",
        ["target_stock_id", "horizon_days"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_event_observations_target_horizon", table_name="event_study_observations")
    op.drop_table("event_study_observations")
    op.drop_index(
        "ix_conditional_results_run_horizon", table_name="conditional_probability_results"
    )
    op.drop_table("conditional_probability_results")
    op.drop_table("portfolio_stress_results")
    op.drop_table("portfolio_risk_metrics")
    op.drop_index("ix_market_regime_observations_run_date", table_name="market_regime_observations")
    op.drop_table("market_regime_observations")
    op.drop_table("lead_lag_metrics")
    op.drop_table("financial_per_share_metrics")
    op.drop_index("ix_event_statistics_run_horizon", table_name="event_study_statistics")
    op.drop_table("event_study_statistics")
    op.drop_index("ix_event_occurrences_stock_date", table_name="event_occurrences")
    op.drop_table("event_occurrences")
    op.drop_index(
        "ix_conditional_probability_runs_created", table_name="conditional_probability_runs"
    )
    op.drop_table("conditional_probability_runs")
    op.drop_index("ix_signals_stock_time", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_prices_stock_date", table_name="prices")
    op.drop_table("prices")
    op.drop_index("ix_portfolio_risk_runs_portfolio_created", table_name="portfolio_risk_runs")
    op.drop_table("portfolio_risk_runs")
    op.drop_table("portfolio_positions")
    op.drop_index("ix_market_regime_runs_end_created", table_name="market_regime_runs")
    op.drop_table("market_regime_runs")
    op.drop_index("ix_market_graph_nodes_run_core", table_name="market_graph_nodes")
    op.drop_table("market_graph_nodes")
    op.drop_index("ix_market_graph_edges_run_type_strength", table_name="market_graph_edges")
    op.drop_table("market_graph_edges")
    op.drop_index("ix_lead_lag_pair_run_significant_confidence", table_name="lead_lag_pair_results")
    op.drop_table("lead_lag_pair_results")
    op.drop_index("ix_financials_stock_available", table_name="financials")
    op.drop_table("financials")
    op.drop_index("ix_factor_scores_run_date_score", table_name="factor_scores")
    op.drop_table("factor_scores")
    op.drop_index("ix_events_type_time", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_event_study_runs_definition_created", table_name="event_study_runs")
    op.drop_table("event_study_runs")
    op.drop_index("ix_stocks_market_status", table_name="stocks")
    op.drop_index(op.f("ix_stocks_industry_id"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_index("ix_relationship_correlations_pair_date", table_name="relationship_correlations")
    op.drop_table("relationship_correlations")
    op.drop_index("ix_relationship_anomalies_run_change", table_name="relationship_anomalies")
    op.drop_table("relationship_anomalies")
    op.drop_table("market_graph_paths")
    op.drop_table("factor_backtest_summaries")
    op.drop_index("ix_factor_backtest_period_run_date", table_name="factor_backtest_periods")
    op.drop_table("factor_backtest_periods")
    op.drop_index(op.f("ix_research_reports_report_type"), table_name="research_reports")
    op.drop_index(op.f("ix_research_reports_as_of_date"), table_name="research_reports")
    op.drop_table("research_reports")
    op.drop_index(
        "ix_relationship_runs_universe_method_created", table_name="relationship_analysis_runs"
    )
    op.drop_table("relationship_analysis_runs")
    op.drop_table("portfolios")
    op.drop_index("ix_market_graph_runs_end_created", table_name="market_graph_runs")
    op.drop_table("market_graph_runs")
    op.drop_index("ix_lead_lag_runs_end_created", table_name="lead_lag_analysis_runs")
    op.drop_table("lead_lag_analysis_runs")
    op.drop_table("industries")
    op.drop_index("ix_fx_rates_pair_date", table_name="fx_rates")
    op.drop_table("fx_rates")
    op.drop_index("ix_factor_runs_type_created", table_name="factor_research_runs")
    op.drop_table("factor_research_runs")
    op.drop_index("ix_event_definitions_active_type", table_name="event_definitions")
    op.drop_table("event_definitions")
    # ### end Alembic commands ###
