"""ROUND62 cross-sectional expected-return challenger framework."""

from personal_alpha_terminal.quant_engine.alpha_engine3.cross_sectional import (
    DEFAULT_PRICE_FEATURES,
    FUNDAMENTAL_FEATURES,
    AlphaEngine3Config,
    AlphaEngine3Evaluation,
    AlphaEngine3Verdict,
    AlphaModelKind,
    CrossSectionalPrediction,
    FeatureAblation,
    FeaturePanel,
    ModelEvidence,
    WalkForwardFold,
    build_forward_labels,
    build_price_feature_panel,
    build_walk_forward_folds,
    evaluate_alpha_engine3,
    evaluate_feature_ablation,
)
from personal_alpha_terminal.quant_engine.alpha_engine3.reality_test import (
    AlignedPerformanceObservation,
    AlphaEngine3RealityTest,
    EconomicMetrics,
    ExposureCounterfactual,
    MarketRegime,
    RealityTestVerdict,
    RegimeMetrics,
    classify_market_regime_as_of,
    compact_reality_status,
    run_alpha_engine3_reality_test,
)

__all__ = [
    "DEFAULT_PRICE_FEATURES",
    "FUNDAMENTAL_FEATURES",
    "AlphaEngine3Config",
    "AlphaEngine3Evaluation",
    "AlphaEngine3Verdict",
    "AlphaModelKind",
    "CrossSectionalPrediction",
    "FeatureAblation",
    "FeaturePanel",
    "ModelEvidence",
    "WalkForwardFold",
    "build_forward_labels",
    "build_price_feature_panel",
    "build_walk_forward_folds",
    "evaluate_alpha_engine3",
    "evaluate_feature_ablation",
    "AlignedPerformanceObservation",
    "AlphaEngine3RealityTest",
    "EconomicMetrics",
    "ExposureCounterfactual",
    "MarketRegime",
    "RealityTestVerdict",
    "RegimeMetrics",
    "classify_market_regime_as_of",
    "compact_reality_status",
    "run_alpha_engine3_reality_test",
]
